modLoader="javafml" #mandatory
loaderVersion="[47,)" #mandatory This is typically bumped every Minecraft version by Forge. See our download page for lists of versions.
license="MIT"
#issueTrackerURL="https://change.me.to.your.issue.tracker.example.invalid/" #optional
[[mods]] #mandatory
# The modid of the mod
modId="beneath" #mandatory
version="${file.jarVersion}" #mandatory
displayName="Beneath" #mandatory
logoFile="beneath.png" #optional
authors="EERussianguy" #optional
description='''
An addon for TFC.
'''
[[dependencies.beneath]] #optional
    modId="tfc" #mandatory
    mandatory=true #mandatory
    versionRange="[0,)" #mandatory
    ordering="NONE"
    side="BOTH"
[[dependencies.beneath]] #optional
    modId="forge" #mandatory
    mandatory=true #mandatory
    versionRange="[47.1.3,)" #mandatory
    ordering="NONE"
    side="BOTH"
[[dependencies.beneath]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.20.1,1.20.2)"
    ordering="NONE"
    side="BOTH"
